name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t my-image .  
      - name: Run tests inside Docker
        run: |
          docker run my-image 
      - name: Check if Docker container is running
        run: |
          docker ps -a